### ISSUE TITLE
Settings' reset doesn't work properly

### ISSUE THREAD

**Issue by Madis0** [TheMegax/fabric-elytra-autopilot#24] opened 2022-01-26 16:50 UTC
Not sure if it is a problem with your library or with the code used to create config:

Reproduce:
1. Open settings
2. Change any number value
3. Save and close settings
4. Open settings

Expected:
"Reset" button to be available

Actual:
"Reset" button is grayed out; when changing the number again, it becomes available but does not reset to the _original_, but rather to the _currently saved_ value.

Minecraft 1.18.1, Elytra AutoPilot 1.3.1, Fabric API 0.46.2

**Comment by TheMegax** [comment] 2022-06-23 23:12
The problem is the code, it's very old by this point. I'm going to replace the old system by a much more robust one by the next update

**Comment by TheMegax** [comment] 2022-06-24 02:55
Fixed in 1.19 update ;]

**Closed as completed by TheMegax** 2022-06-24 02:55 UTC
Labels: bug, high priority
